### PR TITLE
Add support for buildKit and buildType in cmake.buildDirectory

### LINKED ISSUE #17: Qt not found when cmake.buildDirectory uses variables
The extension can not find Qt in our case because the cmake.buildDirectory uses variables. In our example the buildDirectory is `${workspaceFolder}/../CMakeBuild/vscode/${buildKit}/${buildType}`

The error message reported:
`ENOENT: no such file or directory, watch 'c:\Projects\XXX/../CMakeBuild/vscode/${buildKit}/${buildType}'`

### PR DESCRIPTION
**Pull request by tonka3000**
Add support for buildKit and buildType in cmake.buildDirectory

Closes #17

### CODE REVIEW

**Comment by zrno** [comment]
It still doesn't work for me. The status bar says "QtNotFound". 
Not sure what is being searched inside the CMakeCache.txt to find Qt but I assume this line from my file should be used:
```
//The directory containing a CMake configuration file for Qt5.
Qt5_DIR:PATH=C:/SDKs/Qt/Qt5.12.2/5.12.2/msvc2017/lib/cmake/Qt5
```

And this is the output when I click on "QtNotFound": `update state of ExtensionManager`

**Comment by tonka3000** [comment]
Hey @zrno ,

at the momemt I search for `Qt5_DIR` or `Qt5Core_DIR` to get to the directory of Qt, so that should work in your case. So I assume your directory of Qt exists.

The extension search in every directory from the given path for `bin/qmake.exe`, so in your case it start with checking `C:/SDKs/Qt/Qt5.12.2/5.12.2/msvc2017/lib/cmake/Qt5/bin/qmake.exe` and if it is not there it goes one directory up, so in you case `C:/SDKs/Qt/Qt5.12.2/5.12.2/msvc2017/lib/cmake/bin/qmake.exe` and so on and so on.

In your case it should find qmake on `C:/SDKs/Qt/Qt5.12.2/5.12.2/msvc2017/bin/qmake.exe`, is there a `qmake.exe` on your machine in that location?

> And this is the output when I click on "QtNotFound": update state of ExtensionManager

You mean clicking on the button in the bottom toolbar of VS Code, right?

**Comment by tonka3000** [comment]
Hey @zrno ,

I've added a logger in the `develop` branch. Can you please git clone or download the zip of the latest `develop` branch commit, go into the directory and type `npm install`. After that open the folder in VS Code and press F5 to start the extension. Open your C++ project in the new VS Code window and add the following setting to your `settings.json` file

```json
"qttools.loglevel": "debug"
```

Then click on the `Qt not found` button and post the content of the `Qt` output pane here.
Also attach your `CMakeCache.txt` file here.

Thanks in advance

Tonka

**Comment by zrno** [comment]
image

[CMakeCache.txt](https://github.com/tonka3000/vscode-qt-tools/files/5019071/CMakeCache.txt)

Hope this helps. Thanks for the support so far

**Comment by zrno** [comment]
`C:\Projects\CMakeBuild\vscode\Visual Studio Professional 2019 Release - x86\Debug`

This is the actual path where the CMakeCache.txt file is. The output messages say it is looking at:
`c:\Projects\CMakeBuild\vscode\Visual Studio Professional 2019 Release - x86\Debug HAS_GPU\CMakeCache.txt`
Notice the real folder is called `...\Debug\` but the extension is looking into `...\Debug HAS_GPU\`. 
The `Debug HAS_GPU ` string is the name of our current CMake build variant which doesn't match the actual folder name

**Comment by tonka3000** [comment]
Maybe https://github.com/microsoft/vscode-cmake-tools/pull/1369 is the problem?

**Pull request merged**
