### PR TITLE
Add .qss, .ui and .qrc

### PR DESCRIPTION
**Pull request by Marr11317**
Add .qss, .ui and .qrc to package.json to provide syntax highlighting

### CODE REVIEW

**Comment by tonka3000** [comment]
Thanks for your PR.

Please move your `languages` element inside the `contributes` element, otherwise your change won't work (right now it's outside of the `contributes` element and vscode does not recognize it), something like this

```json
	                                        "scope": "resource"
					}
				}
			}
		],
		"languages": [
			{
				"id": "css",
				"extensions": [
					".qss"
				]
			},
			{
				"id": "xml",
				"extensions": [
					".ui",
					".qrc"
				]
			}
		]
	},
	"scripts": {
		"vscode:prepublish": "npm run compile",
		"compile": "tsc -p ./",
		"watch": "tsc -watch -p ./",
```

With this change your PR will work and I will merge it.

Greetings  
Tonka

**Comment by Marr11317** [comment]
Thanks! Sorry, I did not build it on my computer as I thought it was not worth it for such a small change. I will correct it monday.

**Comment by Marr11317** [comment]
done

**Comment by tonka3000** [comment]
Nice. This partially will resovle #9

**Pull request merged**
