### PR TITLE
Add Qt help view

### LINKED ISSUE #39: Search in documentation
In QtCreator, you can press F1 and get help with the current class. Is it possible to add similar functionality to the command palette to open a web page with the selected class? I would suggest providing a search and if it is empty then the class under the cursor will be found.

### PR DESCRIPTION
**Pull request by tonka3000**
Add Qt help webview. The Impl. just use the word under the cursor (no selection!) and just use the Qt docs website https://doc.qt.io/qt-5 . The word will be attached in lowercase. `QWidget` would look like https://doc.qt.io/qt-5/qwidget.html

Closes #39

### CODE REVIEW

**Comment by Shatur95** [comment]
Thanks! Works for me. Is it possible to add a search and the ability for manual search using `https://doc.qt.io/qt-5/search-results.html?q=requestText`?

**Comment by Shatur95** [comment]
I also noticed that you use GitHub Actions. Could you add something like the following to the CI? This will allow to just download the extension after CI without manual build.

**Comment by tonka3000** [comment]
- `CTRL + F` seems not to work in VSCode webview AFAICT
- Manual search should be possible via another command
- Upload CI artifacts should also be possible

I will try to find some spare time in the next few days to check this points.

**Comment by Shatur95** [comment]
> CTRL + F seems not to work in VSCode webview AFAICT

Not sure if this is related, but a similar problem has been resolved in [vscode-godot-tools](https://github.com/godotengine/godot-vscode-plugin/pull/229#issuecomment-692786155).

> Manual search should be possible via another command
> Upload CI artifacts should also be possible

Yeah, it would be nice. Thanks!

**Comment by tonka3000** [comment]
"Find" works (take some time to process) when you click on the area above the view and then press `CTRL + F`. When you click in the view it will not work. VSCode seems not to support the find widget with iframes correctly, see https://github.com/microsoft/vscode/issues/96307

**Comment by Shatur95** [comment]
Thanks for the info!

**Comment by tonka3000** [comment]
Hey @Shatur95 ,

I've added a search command for the Qt help, but there is a problem. The search results are links with `target="_blank"` which is not supported by VSCode webviews with iframe, so you can not click them. When you press the middle mouse button it will open the link in the external browser and that is the only way how you can click them. Maybe the simplest idea to fix that is to open the search directly in the external browser.

I've added artifacts to the `build` CI jobs, so you can easily try it out.

**Comment by Shatur95** [comment]
Thank you! Tested, yes, works for me. If there are so many restrictions in embedding, maybe will be better to just show all documentation in browser?

**Comment by tonka3000** [comment]
Hey @Shatur95 ,

I've also add external browser support. By default the extension launch the webview inside VSCode, but you can turn this off by just set `qttools.useExternalBrowser` to `true`. If've update the `README.md` where I list all the features and limitations.

Let me know I you like it or you miss something.

**Comment by Shatur95** [comment]
Thanks, just what I need.

**Pull request merged**
